### ISSUE TITLE
读取gigaword_chn.all.a2b.bi.ite50.vec文件出错

### ISSUE THREAD

**Issue by Robert201806** [jiesutd/LatticeLSTM#1]
下面这两的向量维度不是50，一个是15，一个是 55， 是这个文件本来的问题，还是我下载过程中传输出错了（没有百度网盘会员，下的真慢）？

森悄 -0.420138 -0.189634 0.346326 -0.235297 -0.389551 -0.588 1.164976 -0.610863 0.073047 0.531165 -3.343037 -0.666090 2.384061 0.129748 -1.972636

系v 0.108717 -0.042028 -2.452340 -0.387857 1.953125 0.230040 2.203831 3.083842 0.400699 -0.449208 1.321026 -2.430978 1.369693 0.100625 -1.246027 -0.846308 -2.649471 0.168484 0.593922 -0.481574 0.546810 -2.844704 -0.956998 -2.017416 1.072134 -1.407300 -0.145390 -0.086188 -0.896394 2.064528 1.660699 0.500353 0.773185 -2.036687 3.072354 0.667415 -0.520374 -1.668948 0.729110 0.385540 -0.868025 0.600913 1.883432 3.111219 -1.039192 1.274076 1.103154 3.524141 -0.77819 -2.084318 -1.281501 -2.526086 -2.124930 -0.793325 -0.496073

**Comment by jiesutd** [comment]
This may be caused by the network problem. Bigram embeddings are not necessary for lattice LSTM, you can check the readme file carefully, only unigram embeddings  *.uni.* and Word Embeddings ctb.* are needed.

**Comment by Robert201806** [comment]
Thank you. I am reading the source code and  also surprised why this file is needed. In source code gaz_file = None so that ctb.*  is not needed.

**Comment by jiesutd** [comment]
Oh, if you want to set gaz_file=None, then it is the baseline without lattice. You should set the gaz_file=ctb.* to build the lattice lstm.

**Comment by Robert201806** [comment]
Thank you. I should read experiments of the paper again.
