### ISSUE TITLE
Demon data

### ISSUE THREAD

**Issue by MrRace** [jiesutd/LatticeLSTM#10]
run the demon-run_demo.sh,it seems request some more data in "onto4ner.cn" directory.So where to get 
demo.train.char, demo.dev.char and demo.test.char?

**Comment by jiesutd** [comment]
Hi @MrRace , thank you very much for your notice.

Sorry but I forgot to add the demo data. I just add them in this repository and you can find them now.

Cheers!

**Comment by PeterPanUnderhill** [comment]
Hi @jiesutd  , it seems there's no such data in the /data directory. Or is it actually in /ResumeNER?

**Comment by jiesutd** [comment]
@PeterPanUnderhill /data directory contains demo data, which is sample data to text if your environment is OK. The resume data is located in /ResumeNER
