### ISSUE TITLE
词典问题

### ISSUE THREAD

**Issue by Wangpeiyi9979** [jiesutd/LatticeLSTM#100]
您好，您的词典是通过对大量语料进行分词得到的吗？能分享一下词典吗，文中给的链接似乎打不开了

**Comment by jiesutd** [comment]
是自动分词得到的。我给了两个链接一个google drive  一个百度网盘，我都能打开。

**Comment by Wangpeiyi9979** [comment]
抱歉，自动分词得到的词典是指的‘ctb.50d.vec’这个文件吗，可是这个文件中好多并不是实体呀

**Comment by Wangpeiyi9979** [comment]
我统计了一下，词典的质量非常差，正确匹配的实体的准确率只有10-2这个数量级，这样的话，我感觉lattice网络基本就是引入的分词的信息。

**Comment by jiesutd** [comment]
> 我统计了一下，词典的质量非常差，正确匹配的实体的准确率只有10-2这个数量级，这样的话，我感觉lattice网络基本就是引入的分词的信息。

ctb.50d.vec 就是自动分词后训练的word embeddings. 并不是实体。 你仔细看看论文就知道了，文章就是用lattice 结构融入词的信息，并不是用的实体表。
