### ISSUE TITLE
大佬您好 我想问下 对于测试集长度长于训练集的训练长度的文本时？

### ISSUE THREAD

**Issue by xuanzebi** [jiesutd/LatticeLSTM#109]
我想问下 对于测试集长度长于训练集的训练长度的文本时？对于这部分长度比训练集设定的最大训练文本长度长的话，在计算P\R\F1时是怎么进行处理的呀？
是截断成两个句子分别预测吗？ 还是对于长于训练集部分的长度进行抛弃，计算PRF1时候也不用它们？

**Comment by jiesutd** [comment]
直接抛弃。你可以在训练时把最大训练文本长度设置大一点就可以解决这个问题。
