### ISSUE TITLE
Decode Bug

### ISSUE THREAD

**Issue by jc-ryan** [jiesutd/LatticeLSTM#111]
在对Ontonotes的测试集进行decode时
从55747行开始，decode出来的内容与原测试集的内容(文本内容，而非标签)不一致
总体而言decode出来的内容比原测试集内容要少一些
其他数据集(除了msra)均有类似情况

**Comment by jiesutd** [comment]
这是因为你的数据集里有太长的句子被过滤了，把下面的数值设置大一点就可以了

https://github.com/jiesutd/LatticeLSTM/blob/24d17f4270f11d2f75046789d8b67eaa2b907dce/utils/data.py#L21
