### ISSUE TITLE
您好，我想请教两个关于数据集的问题

### ISSUE THREAD

**Issue by tyistyler** [jiesutd/LatticeLSTM#113]
1、您在论文中分别提到了bioes和bmeso两种格式，在其他的issues中您提到训练时使用了bioes，请问bmeso有什么作用呢？
2、关于weibo数据集的版本，https://github.com/hltcoe/golden-horse中有两个版本weiboNER.conll.train和weiboNER_2nd_conll.train，二者有一些不同，请问您选择的是2nd么？

**Comment by jiesutd** [comment]
1. 我不记得哪里写了bmeso啊？ bmeso应该和bioes 是一样的。
2. 2nd
