### ISSUE TITLE
代码跑完之后的.model怎么查看

### ISSUE THREAD

**Issue by Ilikemuchmuchmoney** [jiesutd/LatticeLSTM#117]
How to view the .model files

**Comment by jiesutd** [comment]
它是一个model file，你想查看什么？

**Comment by Ilikemuchmuchmoney** [comment]
就是想看一下模型跑完之后它的一个成果，直接下载一个可以查看model文件的软件就可以吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jie Yang"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 晚上8:40
收件人: "jiesutd/LatticeLSTM"<LatticeLSTM@noreply.github.com&gt;; 
抄送: "李双"<1014342403@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jiesutd/LatticeLSTM] 代码跑完之后的.model怎么查看 (#117)





 
它是一个model file，你想查看什么？

**Comment by Ilikemuchmuchmoney** [comment]
我想抽取一段文本（和你这个类似的文本）中的实体，怎么使用.model文件来抽取实体？

**Comment by jiesutd** [comment]
如果你说的是decode新的文本的话，可以看这个被注释掉的command 8-12行
https://github.com/jiesutd/LatticeLSTM/blob/24d17f4270f11d2f75046789d8b67eaa2b907dce/run_demo.sh#L8

**Comment by Ilikemuchmuchmoney** [comment]
非常非常感谢
