### ISSUE TITLE
测试自己的数据

### ISSUE THREAD

**Issue by zelin-x** [jiesutd/LatticeLSTM#126]
请问该如何测试自己的数据集，对于那种没有标签的初始数据

**Comment by tianke0711** [comment]
同问

**Comment by jiesutd** [comment]
给每个字后面加上一个伪标签O即可，保持格式和训练数据格式一样。

见 O
钱 O
眼 O
开 O
的 O
师 O
父 O
果 O
真 O
就 O
上 O
钩 O
了 O
。 O

金 O
蟾 O
至 O
此 O
成 O
为 O
财 O
富 O
象 O
征 O

**Comment by tianke0711** [comment]
@jiesutd 谢谢
