### ISSUE TITLE
Batch_size

### ISSUE THREAD

**Issue by hrshy0629** [jiesutd/LatticeLSTM#130]
训练起来非常的慢，我发现主要是因为batch_size在main.py中被设置为1了，而且改了这个参数后，会在model/latticelstm.py：142行提醒报错，初步猜想是作者并没有进行batch_size的其他值的调试，或许会导致一些其他的bug产生。哪位大佬有空能够修正下batch_size的问题吗？

**Comment by jiesutd** [comment]
目前的code只支持batch_size=1
