### ISSUE TITLE
Data set ontonotes-4.0

### ISSUE THREAD

**Issue by GaoYb923** [jiesutd/LatticeLSTM#135]
Hi jiesutd,
I've got ontonotes-4.0 copyright  from LDC, and tryed to split the NER data set by myself.
But I've got a different size of data set, especially on dev and test set.
I want to reimplement the same as your split on OntoNotes-4.0 dataset.
I can prove that i have ontonotes-4.0 copyright.
Could you please send me your split
gaoyunbo923@buaa.edu.cn
best wish

**Comment by jiesutd** [comment]
communicated through email.
