### ISSUE TITLE
Achieves 93.18% F1-value on MSRA dataset, where to find this dataset

### ISSUE THREAD

**Issue by qichaotang** [jiesutd/LatticeLSTM#2]
Hi, 
I see
It achieves 93.18% F1-value on MSRA dataset, which is the state-of-the-art result on Chinese NER task.
But, I try to find by google, I can't find this MSRA dataset. Please ask where I can find this dataset.

**Comment by jiesutd** [comment]
You may look at this link: http://sighan.cs.uchicago.edu/bakeoff2006/instructions.html

**Comment by qichaotang** [comment]
Thanks your replay, but this url can't download datas, I can download datas by https://github.com/SUDA-HLT/NewStudents/blob/master/nlp-projects/named-entity-recognition/MSRA/msra_train_bio

**Comment by jiesutd** [comment]
Great!

**Comment by wwwjs** [comment]
MSRA dataset only has train set and test set. How can I get dev_set if I use MSRA dataset?
