### ISSUE TITLE
Maybe something wrong, the training spent a long time ,but the performance is too low in demo data

### ISSUE THREAD

**Issue by OYE93** [jiesutd/LatticeLSTM#20]
Hi Jie, thank for your works on Chinese NER, I downloaded the code and embedding files, and run the demo, however the training spent a long time, the performance is not good, f-value is adout 0.4 after 50 epoch. But I didn't know where I did wrong.
Environment: python2.7, pytorch0.3.0, gpu1080
Thanks!

**Comment by jiesutd** [comment]
Hi , the demo only use a very limited data. It is only used for demo. So it is reasonable that the performance is low. You need to change your own data to train your own model.
