### ISSUE TITLE
About the speed of training on MSRA dataset...

### ISSUE THREAD

**Issue by DaveYin** [jiesutd/LatticeLSTM#23]
Excuse me, I have some trouble training your model on MSRA dataset with a GTX 1080Ti card. I've found the speed of training is quite slow. So, may I know your solution to this problem? (Note: The video memory almost runs out, but there is still much unused computing power left.)

**Comment by jiesutd** [comment]
Hi, as this code is not implemented in batch. So it is not as faster as the batched implementation ( such as NCRF++).
