### ISSUE TITLE
代码的一些疑问

### ISSUE THREAD

**Issue by Cbird-coder** [jiesutd/LatticeLSTM#24]
你好。在查阅ACL2018时，看见您的论文。按照您论文以及实验代码中的思想，我想确认几点问题：
1、完全摒弃了char特征（ps：代码中未看见通过lstm提取字特征），是不是没有结合char特征和Lattice提取出的特征，只是单单使用Lattice提取出的特征？
2、代码中的bi_word也就是代表了词信息，但是在LatticeLSTM中并未参与计算？这个是没有使用么？
3、仅仅使用Lattice网络在长期依赖的问题处理上，能不能保证和lstm能达到相同的效果？有没有一些论证呢？

**Comment by jiesutd** [comment]
你好，
1. 我们没有摒弃char 的特征，实际上我们的框架是基于char 的，只是在char lstm的基础上添加了word 的shortcut。因为代码是从之前的NCRF++ 修改的，所以有些变量名没有修改。code 里面的words/biwords 实际上指的是chars/bichars. 
2. 如1所述， biword 实际上指的是bichar (也就是char bigram), 这里没有使用，因为我们发现加上bichar 效果并不好。详情请参见论文Figure 4.
3. 如1所述，我们并没有仅仅用lattice, 而是综合了lattice word 和char lstm. 效果提升明显。
