### ISSUE TITLE
尝试过类似方法在中文分词的效果

### ISSUE THREAD

**Issue by xpjandy** [jiesutd/LatticeLSTM#27]
1.这种边界信息对分词应该也有帮助啊，有尝试过吗？
2.paper中lattice用到的分词，是现成的分词器，还是用的无监督分词来产生词表啊？

谢谢。

**Comment by jiesutd** [comment]
你好，

1. 我最近做过实验，对分词有明显的帮助。实验结果在我们后面的一篇论文中会有具体分析，等论文公开了你可以关注。
2. 你问的太不具体了。文章好几处都提到的分词，但是我们的lattice 不需要分词信息，我们的latticeLSTM for NER 是segmentation free的。lattice 需要的是匹配的词表而不是分词的结果，匹配的词表的来源是通过输入句子和词典匹配得来的。而这个词典的来源可以有很多，比如领域内专有名词的列表；也可以是用个分词器对生语料进行切分，把得到的词放入词表。当然无监督分词或者其它的算法也可以得到词表，我们最近的那篇论文也会涉及这一方面。
