### ISSUE TITLE
MSRA数据集

### ISSUE THREAD

**Issue by HaimianYu** [jiesutd/LatticeLSTM#31]
您好：
      我在GitHub上下载的MSRA数据集是BIO格式的标签，您好像使用的是BMES格式的标签，请问能不能通过百度云或者其他方式分享一下呢

**Comment by jiesutd** [comment]
I have written a tag converter script here: https://github.com/jiesutd/NCRFpp/blob/master/utils/tagSchemeConverter.py

You can try it. Here "BMES" should be the same with "BIOES".

**Comment by HaimianYu** [comment]
谢谢

**Comment by HaimianYu** [comment]
请问，您论文中在resume数据集上的结果，是直接使用您代码中设置的超参数得到的，还是需要重新调参数呢？

**Comment by jiesutd** [comment]
The same hyper parameters.

**Comment by js418** [comment]
想问一下MSRA数据集在哪里可以获得？
