### ISSUE TITLE
模型怎么用GPU，需要改几处？

### ISSUE THREAD

**Issue by zxy951005** [jiesutd/LatticeLSTM#38]
gpu=True，但是也没用GPU, 哪儿需要改动，model后面加个cuda()就完了吗？还是还有其他也要改。

**Comment by zxy951005** [comment]
没用上batch所以速度好慢啊，训练一天才8个epoch > _ < 。谢谢作者，回复好快。

**Comment by Kiwisher** [comment]
I am a little bit confused why can't it use batch during training..?

**Comment by jiesutd** [comment]
> I am a little bit confused why can't it use batch during training..?

Because it is hard to implement the real batched lattice LSTM, as each input has a different shortcut link. The batched version is possible, but it is a little complicated.

**Comment by songtaoshi** [comment]
does the batched version meaning we should padding inner padding?
