### ISSUE TITLE
The training time is too long. 

### ISSUE THREAD

**Issue by Robert201806** [jiesutd/LatticeLSTM#4]
I try to train a model on msra data using a nvidia 1080 Ti,  and it takes about 120 seconds on 500 sentences. It is acceptable on small data set, but if the data set is larger, for instance, 5 times bigger than msra, the training time is too long.

Is there any way to speed up the training speed?

**Comment by jiesutd** [comment]
Currently the code only process sentence one by one, the batched version has not been implemented yet. I am afraid the speed can not be improved until the batched implementation finished. I do not have time to implement it recently, unfortunately.

**Comment by jiesutd** [comment]
Yes, the different number of matching words is one problem, for both the beginning character and end character. Padding and mask can solve this problem but need more code work.
