### ISSUE TITLE
I upgraded the code to support python3.5 and pytorch 0.4.1 which passed the tests.

### ISSUE THREAD

**Issue by Shun14** [jiesutd/LatticeLSTM#41]
As title shows, I upgraded the code.If you want to use the code on pytorch 0.4.1 ,please refer to this.
[new_version](https://github.com/Shun14/LatticeLSTM)

**Comment by Biaocsu** [comment]
well done

**Comment by Biaocsu** [comment]
@Shun14  Well done

**Comment by jiesutd** [comment]
Great! Thanks!

**Comment by Biaocsu** [comment]
@Shun14  when I use your upgraded code to test a file, I happend to meet this error: 
Traceback (most recent call last):
  File "main.py", line 447, in <module>
    decode_results = load_model_decode(model_dir, data, 'raw', gpu, seg)
  File "main.py", line 354, in load_model_decode
    speed, acc, p, r, f, pred_results = evaluate(data, model, name)
  File "main.py", line 152, in evaluate
    gaz_list,batch_word, batch_biword, batch_wordlen, batch_wordrecover, batch_char, batch_charlen, batch_charrecover, batch_label, mask  = batchify_with_label(instance, data.HP_gpu, True)
  File "main.py", line 195, in batchify_with_label
    mask[idx, :seqlen] = torch.Tensor([1]*seqlen.cpu().numpy().tolist())
AttributeError: 'int' object has no attribute 'cpu'
Could you help me find out where is wrong? thanks

**Comment by Shun14** [comment]
> @Shun14 when I use your upgraded code to test a file, I happend to meet this error:
> Traceback (most recent call last):
> File "main.py", line 447, in 
> decode_results = load_model_decode(model_dir, data, 'raw', gpu, seg)
> File "main.py", line 354, in load_model_decode
> speed, acc, p, r, f, pred_results = evaluate(data, model, name)
> File "main.py", line 152, in evaluate
> gaz_list,batch_word, batch_biword, batch_wordlen, batch_wordrecover, batch_char, batch_charlen, batch_charrecover, batch_label, mask = batchify_with_label(instance, data.HP_gpu, True)
> File "main.py", line 195, in batchify_with_label
> mask[idx, :seqlen] = torch.Tensor([1]*seqlen.cpu().numpy().tolist())
> AttributeError: 'int' object has no attribute 'cpu'
> Could you help me find out where is wrong? thanks

Maybe your pytorch version is not 0.4.1.I modified the code 
`[1]*seqlen.cpu().numpy().tolist()`
whose original code like this `[1]*seqlen`  because of the difference between two versions of the pytorch.

**Comment by Biaocsu** [comment]
@Shun14  This time I'm sure I use Pytorch 0.4.1，but python 3.6
However, I get plenty of wanrnings as well as error like this:
fout.write(content_list[idx][0][idy].encode('utf-8') + " " + predict_results[idx][idy] + '\n')
TypeError: can't concat str to bytes
are you sure there is nothing wrong when you run the code?

**Comment by Shun14** [comment]
Oh I ran the test for the status of train and test.The error is about encoding. You can modified this part like this one to solve it.`fout.write(str(content_list[idx][0][idy].encode('utf-8')) + " " + predict_results[idx][idy] + '\n')`

**Comment by Biaocsu** [comment]
@Shun14 thanks! and I use "warnings.filterwarnings" to fiter the warnings which makes it looks better!
Anyhow, thank you for your help
