### ISSUE TITLE
About regularization

### ISSUE THREAD

**Issue by Kiwisher** [jiesutd/LatticeLSTM#42]
I read in the paper that you set a weight-decay in the optimizer, but I didn't see that term in your initialization of optimizer in main.py here. I wonder if I have skipped something or you really didn't set the regularization in your code? Thanks.

**Comment by jiesutd** [comment]
https://github.com/jiesutd/LatticeLSTM/blob/3f960348ea07b065afff653949046f09470332f4/main.py#L253

**Comment by jiesutd** [comment]
For the regularization, yes we found the regularization does not affect the results a lot, so we removed this part. As the dropout is already a good way to avoid overfitting.
