### ISSUE TITLE
Which pretrained character embeding is used？

### ISSUE THREAD

**Issue by sunhf** [jiesutd/LatticeLSTM#45]
In character-based NER, which one is used as the pretrained embeding?gigaword_chn.all.a2b.uni.ite50.vec or joint4.all.b10c1.2h.iter17.mchar?

**Comment by jiesutd** [comment]
The first one, i.e. `gigaword_chn.all.a2b.uni.ite50.vec`

**Comment by sunhf** [comment]
Thanks a lot!
