### ISSUE TITLE
关于character baseline效果

### ISSUE THREAD

**Issue by sunhf** [jiesutd/LatticeLSTM#46]
我用tensorflow复现文中的字模型baseline效果，使用了相同的实验配置和embeding，ontonotes 4 test数据集上只得到了61左右的f值，微博语料则要高一些。请问如果用您的代码，需要做什么改动来跑字模型的baseline效果呢？

**Comment by jiesutd** [comment]
Simply set the gas_file = None
https://github.com/jiesutd/LatticeLSTM/blob/3f960348ea07b065afff653949046f09470332f4/main.py#L399


On 16 Jan 2019, at 4:38 AM, sunhf <notifications@github.com<mailto:notifications@github.com>> wrote:


我用tensorflow复现文中的字模型baseline效果，使用了相同的实验配置和embeding，ontonotes 4 test数据集上只得到了61左右的f值，微博语料则要高一些。请问如果用您的代码，需要做什么改动来跑字模型的baseline效果呢？

**Comment by sunhf** [comment]
好的，非常感谢

**Comment by yangl326-Dylan** [comment]
@sunhf 你好，你自己实现的字模型tensorflow版是否有在msra上做过实验哈？我在训练过程加入dev数据集进行验证，dev数据集上的指标很低，epoch=10左右时，dev上正确标注的实体任然是0，但是训练的F1值已经到了91%。不清楚是否我的实现有问题。
