### ISSUE TITLE
预训练的字向量和词向量

### ISSUE THREAD

**Issue by goingcoder** [jiesutd/LatticeLSTM#53]
你好，请问在预训练embedding时有什么tricks吗？我发现自己使用word2vec训练的字向量在NER上效果并不好。

**Comment by jiesutd** [comment]
效果有多不好？对于embedding训练时我们没用什么trick, 直接是word2vec 训练，而且是15年训练的这次随便拿来使用的， 祖传embedding...

**Comment by goingcoder** [comment]
> 效果有多不好？对于embedding训练时我们没用什么trick, 直接是word2vec 训练，而且是15年训练的这次随便拿来使用的， 祖传embedding...

比随机的差几个点

**Comment by Coder-XIAOKAI** [comment]
> 你好，请问在预训练embedding时有什么tricks吗？我发现自己使用word2vec训练的字向量在NER上效果并不好。

您好，我想对自己的词典预训练embedding，想请教您用的word2vec模型是哪个，该如何使用，输入的应该是词语还是句子
