### ISSUE TITLE
在计算字符cell时，一般有两个状态c和h，

### ISSUE THREAD

**Issue by goingcoder** [jiesutd/LatticeLSTM#54]
通常c的计算，都会考虑前一个字符的c状态，为什么论文中这部分没有呢？为什么论文只考虑来当前字符相关的所有词的c状态呢？

**Comment by jiesutd** [comment]
我们都试过，对于有匹配的词来说，把之前字的c加进去效果有所降低（依然比baseline 好很多），所以就没用这个了。可能是不同的参数类型混在一起时对训练有所干扰。

**Comment by goingcoder** [comment]
> 我们都试过，对于有匹配的词来说，把之前字的c加进去效果有所降低（依然比baseline 好很多），所以就没用这个了。可能是不同的参数类型混在一起时对训练有所干扰。

谢谢解释。
