### ISSUE TITLE
为什么这里显示enumerate has no attribute next

### ISSUE THREAD

**Issue by ziqiYang19960522** [jiesutd/LatticeLSTM#62]
# build iter
 seq_iter = enumerate(scores)
 # bat_size * from_target_size * to_target_size
 _, inivalues = seq_iter.next()

**Comment by jiesutd** [comment]
？？Please give more description.

**Comment by ziqiYang19960522** [comment]
Thanks for your attention! I have fixed the problem by using python3.6.
