### ISSUE TITLE
请问如何处理softword的词向量？

### ISSUE THREAD

**Issue by 18817835685** [jiesutd/LatticeLSTM#63]
首先很感谢您提供的代码，您论文中提到使用词分割的标签作为soft feature，并将分词标签转化为了标签向量，请问标签向量是随机初始化并随着训练一起fine tune的还是使用了某种预训练的方式得到的？

**Comment by jiesutd** [comment]
分词的标签只有B, M, E, S几种，这是预训练没有意义，直接随机初始化即可

**Comment by 18817835685** [comment]
好的 谢谢您
