### ISSUE TITLE
代码一些疑问

### ISSUE THREAD

**Issue by wwwjs** [jiesutd/LatticeLSTM#66]
您好，在看代码时，我发现在utils/data.py里面的 def build_gaz_alphabet(self, input_file)函数中，您设置条件： if len(line) > 3:    但其实每行数据都多出个换行符，是否应该将其改为：if len(line)>4， 或者利用strip()先去掉换行符？？

**Comment by jiesutd** [comment]
这应该是用来排除空行的，len(line) > 3 或者 >4 应该都行。
