### ISSUE TITLE
如何预测新的数据集？

### ISSUE THREAD

**Issue by jc-ryan** [jiesutd/LatticeLSTM#69]
请问一下您的代码里有用来加载模型以预测新的测试集的那部分代码吗，我找了很久没有找到，是需要自己写吗？

**Comment by jiesutd** [comment]
You can see this demo: https://github.com/jiesutd/LatticeLSTM/blob/24d17f4270f11d2f75046789d8b67eaa2b907dce/run_demo.sh#L8

**Comment by jc-ryan** [comment]
> You can see this demo:
> 
> https://github.com/jiesutd/LatticeLSTM/blob/24d17f4270f11d2f75046789d8b67eaa2b907dce/run_demo.sh#L8

哦哦，谢谢
