### ISSUE TITLE
python3+pytorc1.0.0下程序运行

### ISSUE THREAD

**Issue by fyh97** [jiesutd/LatticeLSTM#71]
有人在python3+pytorc1.0.0运行过该程序吗？感觉改代码改到崩溃了。

**Comment by jiesutd** [comment]
你可以试试这个python 3的分支https://github.com/bamtercelboo/LatticeLSTM

我还没有时间测试。

**Comment by leedavid312** [comment]
您好，在 python 3.7+pytorch1.0.1 运行，会报错(RuntimeError: cuda runtime error (59) : device-side assert triggered at...)，不确定是否为label初始化不是由0开始的缘故，即使label改成从0开始，依然报错。

**Comment by Biaocsu** [comment]
@fyh97 你好，请问你有没有做升级代码到pytorch >1.0.0的工作呢？

**Comment by libing125** [comment]
This code works[https://github.com/bamtercelboo/LatticeLSTM](url)

**Comment by fxuestc** [comment]
@fyh97  改完了吗？
