### ISSUE TITLE
多GPU并行训练

### ISSUE THREAD

**Issue by yutong007X** [jiesutd/LatticeLSTM#74]
因为此模型运行在我的一块GPU上（共有两块TITAN X），训练很慢（大概3000s/epoch）,请问此模型是否可以进行多GPU并行训练？比如应该如何修改代码?或者其它方法的优化来提高收敛速度。期待您的回复~

**Comment by jiesutd** [comment]
速度慢的瓶颈不是GPU不够，而是我没有实现batch 运算的版本，lattice  lstm构建的batch比较复杂，我暂时没有时间实现。

**Comment by yutong007X** [comment]
了解了解 非常感谢您的回复！！
