### ISSUE TITLE
Ontonotes4数据集切分咨询

### ISSUE THREAD

**Issue by SABER-LOVE** [jiesutd/LatticeLSTM#75]
您好，
那篇论文《Named Entity Recognition with Bilingual Constraints》我看了，但是还是想咨询一下，是不是Ontonotes4中的./chinese/annotations文件夹下的数据集，除了./nw/xinhua中的chtb001-0325 和另一个文件下的chtb1000-1078按奇偶分为dev和test，./chinese/annotations中其它文件夹里面的数据全部作为train？

**Comment by jiesutd** [comment]
你好，具体切分方式时间太久我记不清了。你有Ontonotes4的数据的话，留个邮箱我把数据发给你。

**Comment by SABER-LOVE** [comment]
好的，谢谢。我的邮箱是ayuwwk@foxmail.com
