### ISSUE TITLE
ontonotes数据集

### ISSUE THREAD

**Issue by goingcoder** [jiesutd/LatticeLSTM#78]
您好，我最近在实验对比，能给我发一份OntoNote4数据集么？我发现我找到的数据和您论文中的句子数不一致，根据您论文中提供的参考文献找到的数据只有train和test，句子的数量分别为15724，8249,而您论文中的数据在三个数据集上的统计结果分别15.7K，,4.3K，4.3K，似乎后面两项加起来为8.6K，差距有点大。感谢！ nlp_zhang@qq.com

**Comment by jiesutd** [comment]
Due to the copyright limitation, I can't share you with the Ontonotes data unless you prove you have the Ontonotes 4 access license.
