### ISSUE TITLE
新数据集问题

### ISSUE THREAD

**Issue by luluforever** [jiesutd/LatticeLSTM#80]
您好，为什么我把数据换为医疗数据后，效果极低，F1值低到1%，这是为什么呢？我在BILESTM-CRF上面的可以到80%以上

**Comment by jiesutd** [comment]
请确认你的实验设置是否正确

**Comment by luluforever** [comment]
> 
> 
> 请确认你的实验设置是否正确

我就只是直接将数据换为了医疗数据，就很纳闷，不应该这么低的

**Comment by jiesutd** [comment]
你给的信息太少，没法分析。可以给出实验的log， 或许可以看出你实验设置上的问题。

**Comment by luluforever** [comment]
> 
> 
> 你给的信息太少，没法分析。可以给出实验的log， 或许可以看出你实验设置上的问题。

谢谢你们，刚刚把数据集重新清洗了一遍，转化为BIOES后，同时把编码统一后正常了，谢谢

**Comment by Jiaxin-Wen** [comment]
> > 你给的信息太少，没法分析。可以给出实验的log， 或许可以看出你实验设置上的问题。
> 
> 谢谢你们，刚刚把数据集重新清洗了一遍，转化为BIOES后，同时把编码统一后正常了，谢谢

请问数据清洗是如何做的？　以及bioes相对于bio是有明显提升吗
