### ISSUE TITLE
MSRA数据集

### ISSUE THREAD

**Issue by berryxue** [jiesutd/LatticeLSTM#81]
您好，我在https://github.com/OYE93/Chinese-NLP-Corpus/tree/master/NER/MSRA这里获得的MSRA的数据集的train与test的各项统计指标有一些不一致，请问您可以分享一下数据集吗

**Comment by jiesutd** [comment]
MSRA的数据貌似有第三届和第四届测评两个版本，可能是版本不一样导致的，不过我也不确定你那个是什么版本。
