### ISSUE TITLE
ontonotes数据集切分问题

### ISSUE THREAD

**Issue by berryxue** [jiesutd/LatticeLSTM#82]
您好，ontonotes数据集我参考了您文章中提到的那篇论文《Named Entity Recognition with Bilingual Constraints》，但实际切分出的跟您的统计数据有一些差距，请问您能发给我一份切分的数据吗，我已经获得access，如果您需要看access我可以通过邮箱发给您，我的邮箱是xuemengge@iie.ac.cn
另外，想麻烦您跟您确认一下，论文中四份数据集都是用的BMES标注标准吗
若您回复，不胜感激！

**Comment by jiesutd** [comment]
是的，用的都是BIOES的标注方式。
