### ISSUE TITLE
有关论文公式的问题

### ISSUE THREAD

**Issue by rao-ma** [jiesutd/LatticeLSTM#83]
请问论文里的公式13中的h_{b}^c是否应为h_{b-1}^c，比如“大桥”用输入了“江”后得到的hidden state和"大桥"的词向量作为输入。目前是输入了"大"后的hidden state和"大桥"的词向量作为lstm的输入。

**Comment by jiesutd** [comment]
两种我都尝试过，效果都能有提高，只是现在公式里面（大+大桥）的提升效果更明显。

**Comment by rao-ma** [comment]
谢谢回复，就是感觉和经验不太符合
